export enum DRAW_TYPE {
  LINES = 'LINES',
  TRIANGLES = 'TRIANGLES',
  POINTS = 'POINTS',
  LINE_STRIP = 'LINE_STRIP',
  LINE_LOOP = 'LINE_LOOP',
  TRIANGLE_STRIP = 'TRIANGLE_STRIP',
  TRIANGLE_FAN = 'TRIANGLE_FAN',
}

export enum COLORING_TYPE {
  COLOR,
  TEXTURE,
}
